services:
    core.handle.intervention:
        class: CoreBundle\Service\HandleIntervention
        arguments: ["@doctrine"]

    core.handle.plan:
            class: CoreBundle\Service\HandlePlan
            arguments: ["@doctrine", "@core.handle.intervention"]

    core.twig_extension:
        class: CoreBundle\Twig\CoreExtension
        arguments: ["@doctrine", "@translator"]
        public: false
        tags:
            - { name: twig.extension }

    core.parser_csv:
        class: CoreBundle\Service\ParseCSV
