services:
    core.handle.intervention:
        class: CoreBundle\Service\HandleIntervention
        arguments: ["@doctrine"]

    lke_blog.twig_extension:
        class: CoreBundle\Twig\CoreExtension
        public: false
        tags:
            - { name: twig.extension }
