services:
    core.handle.intervention:
        class: CoreBundle\Service\HandleIntervention
        arguments: ["@doctrine"]

    core.handle.plan:
            class: CoreBundle\Service\HandlePlan
            arguments: ["@doctrine", "@core.handle.intervention"]

    lke_blog.twig_extension:
        class: CoreBundle\Twig\CoreExtension
        public: false
        tags:
            - { name: twig.extension }
