<?php

namespace CoreBundle\Repository;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllParent()
    {
        $qb = $this->createQueryBuilder('i')
                    ->leftJoin('i.child', 'c')
                    ->addSelect('c')
                    ->where('i.parent IS NULL');

        return $qb->getQuery()->getResult();
    }
}
