<?php

namespace CoreBundle\Repository;

use CoreBundle\Entity\Enterprise;

/**
 * InterventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllParent()
    {
        $qb = $this->createQueryBuilder('i')
                    ->leftJoin('i.child', 'c')
                    ->addSelect('c')
                    ->where('i.parent IS NULL');

        return $qb->getQuery()->getResult();
    }

    public function findByEnterprise(Enterprise $enterprise)
    {
        $qb = $this->createQueryBuilder('i')
            ->leftJoin('i.child', 'c')
            ->addSelect('c')
            ->where('i.parent IS NULL')
            ->andWhere('i.enterprise = :enterprise')
            ->setParameter('enterprise', $enterprise);

        return $qb->getQuery()->getResult();
    }

    public function getOrphelinIntervention(Enterprise $enterprise)
    {
        $qb = $this->createQueryBuilder('i')
                    ->where('i.enterprise = :enterprise')
                    ->andWhere('i.plan IS NULL')
                    ->setParameter('enterprise', $enterprise)
                    ->orderBy('i.createdAt', 'ASC');

        return $qb->getQuery()->getResult();
    }
}
